server.port: 8888

spring.profiles.active: dev

spring:
  batch:
    job:
      initialize-schema: always
      enabled: false
    config:
      chunkSize: 100
      poolSize: 4

open.api:
  key: f6331b02fa084486b9e2de875558c3e0
  store:
    url: https://openapi.gg.go.kr/RegionMnyFacltStus
    type: json
    pSize: 100