spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: local

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%-5level] %logger.%method:line%line - %msg%n"
  level:
    root: debug
    org:
      hibernate:
        type:
          descriptor:
            sql: trace