spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: local

logging:
  level:
    root: debug
    org:
      hibernate:
        type:
          descriptor:
            sql: trace